// 2025_kw4-Memory/src/components/Memory.tsx
import { MouseEvent } from "react";
import MemoryItem from "./MemoryItem";
import { v4 as uuid } from "uuid";
import MemoryCard from "../MemoryCard";

type MemoryProps = {
  cardCount: number;
};

function shuffleArray<T>(array: T[]): T[] {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
  return array;
}

export default function Memory({ cardCount }: MemoryProps) {
  let images = [
    "1.webp",
    "2.webp",
    "3.webp",
    "4.webp",
    "5.webp",
    "6.webp",
    "7.webp",
    "8.webp",
    "9.webp",
    "10.webp",
    "11.webp",
    "12.webp",
    "13.webp",
    "14.webp",
  ];

  images = shuffleArray(images);

  const col = Math.ceil(Math.sqrt(cardCount));

  let lastClicked: string | null = null;

  const style = {
    gridTemplateColumns: `repeat(${col}, 1fr)`,
  };

  let cards: MemoryCard[] = [];

  const lcards: MemoryCard[] = [];
  for (let i = 0; i < cardCount / 2; i++) {
    const selectedImage = images[0];
    images.shift();
    lcards.push(new MemoryCard(uuid(), selectedImage));
  }

  cards = [...lcards, ...lcards];

  cards = shuffleArray(cards);

  const clickHandler = (e: MouseEvent<HTMLDivElement>) => {
    const id = e.currentTarget.dataset.id;

    if (!id) {
      return;
    }

    if (lastClicked === id) {
      lastClicked = null;
      alert("match");
      return;
    }

    lastClicked = id;
  };

  return (
    <div className="grid" style={style}>
      {cards.map((card) => {
        return <MemoryItem clickHandler={clickHandler} card={card} />;
      })}
    </div>
  );
}

// 2025_kw4-Memory/src/app/components/memory/memory.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { MemoryCard } from '../../models/memory-card/memoryCard.model';
import { v4 as uuid } from 'uuid';
import { MemoryItemComponent } from '../memory-item/memory-item.component';

@Component({
  selector: 'app-memory',
  standalone: true,
  imports: [CommonModule, MemoryItemComponent],
  templateUrl: './memory.component.html',
  styleUrl: './memory.component.css',
})
export class MemoryComponent {
  private images = [
    '1.webp',
    '2.webp',
    '3.webp',
    '4.webp',
    '5.webp',
    '6.webp',
    '7.webp',
    '8.webp',
    '9.webp',
    '10.webp',
    '11.webp',
    '12.webp',
    '13.webp',
    '14.webp',
  ];

  protected moves: number = 0;

  private cardsCount = 20;
  private col: number;
  protected gridStyle;
  protected cards: MemoryCard[] = [];
  protected activeCards: MemoryCard[] = [];
  protected foundCards: MemoryCard[] = [];

  public constructor() {
    this.images = this.shuffleArray(this.images);
    this.col = Math.ceil(Math.sqrt(this.cardsCount));

    this.gridStyle = {
      gridTemplateColumns: `repeat(${this.col}, 1fr)`,
    };

    const lcards: MemoryCard[] = [];
    for (let i = 0; i < this.cardsCount / 2; i++) {
      const selectedImage = this.images[0];
      this.images.shift();
      const cardId = uuid();
      lcards.push({ id: cardId, image: selectedImage });
      lcards.push({ id: cardId, image: selectedImage });
    }

    this.cards = this.shuffleArray(lcards);

    this.cards = this.cards.map((card, idx) => ({
      ...card,
      index: idx,
    }));
  }

  private shuffleArray<T>(array: T[]): T[] {
    for (let i = array.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
  }

  protected clickHandler(card: MemoryCard) {
    this.moves++;
    if (this.activeCards.length < 1) {
      this.activeCards.push(card);
      return;
    }

    if (this.activeCards.length >= 2) {
      this.activeCards = [];
      this.activeCards.push(card);
      return;
    }

    // match case
    if (this.activeCards[this.activeCards.length - 1].id === card.id) {
      this.foundCards.push(this.activeCards[this.activeCards.length - 1]);
      this.foundCards.push(card);
      this.activeCards = [];
      return;
    }

    this.activeCards.push(card);
  }
}

<div>
  <div>Moves: {{ moves }}; Found Pairs = {{ foundCards.length / 2 }}</div>
  <div class="grid" [style]="gridStyle">
    <app-memory-item
      class="card"
      *ngFor="let card of cards"
      [card]="card"
      [activeCards]="activeCards"
      (clickEvent)="clickHandler($event)"
      [foundCards]="foundCards"
    />
  </div>
</div>
